<?php if ($block->getData('title')) : ?>
    <div class="block-content">
        <?php
        $base_path = "http://example.com/static/version1621615591/frontend/Magento/luma/vi_VN/images/";
        $images = [];
        for($x = 1; $x <= 20; $x++){
            $image_url = $base_path . $x . ".png";
            array_push($images, $image_url);
        }
        $er_url = "https://portal.vietcombank.com.vn/Usercontrols/TVPortal.TyGia/pXML.aspx?b=68";
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, $er_url);
        curl_setopt($ch, CURLOPT_FAILONERROR, 1);
        curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_TIMEOUT, 15);
        curl_setopt($ch, CURLOPT_VERBOSE, true);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
        $res = curl_exec($ch);
        curl_close($ch);
        $xml = simplexml_load_string($res);
        $json = json_encode($xml);
        $rs = json_decode($json, TRUE);
        echo '<table id="currency">';
        echo  "<thead><tr>
        <th>Mã ngoại tệ</th>
        <th>Tên ngoại tệ</th>
        <th>Mua vào</th>
        <th>Bán ra</th>
        <th>Chuyển khoản</th>
        </tr></thead>";
        ?>
        <style>
        table,
        tr,
        th,
        td {
            font-size: 13px;
            font-family: 'Roboto', sans-serif;
            border-collapse: collapse;
            border: 1px solid #D6DBDF ;
            text-align: center !important;
            vertical-align: middle !important;
        }
        th{
            padding: 10px; 
            background-color: #1B4F72;
            color: #ECF0F1 ;
            min-width: 100px;
        }
        span .span{
            padding-bottom: 10px;
        }
        td{
            position: relative;
        }
        .curcode{
            margin: 0px !important;
            display: inline-block;
            position: absolute;
            right: 20px;
            bottom: 10px
        }
        .flag{
            display: inline-block;
            position: absolute;
            top: 5px;
            left: 20px;
        }
        </style>
        <?php
        $i = 0;
        foreach ($rs["Exrate"] as $r) {
        $r = $r["@attributes"];
        echo "<tr>";
        echo "<td>";
        echo '<img class="flag" width="30px" src="' . $images[$i] . '" alt="flag">';
        $i += 1;
        echo '<p class="curcode">' . $r["CurrencyCode"] . '</p>';
        echo "</td>";
        echo "<td>";
        echo $r["CurrencyName"];
        echo "</td>";
        echo "<td>";
        echo $r["Buy"];
        echo "</td>";
        echo "<td>";
        echo $r["Sell"];
        echo "</td>";
        echo "<td>";
        echo $r["Transfer"];
        echo "</td>";
        echo "</tr>";
        }
        echo "</table>";
        ?>
    </div>
    <?php endif; ?>
