<?php if ($block->getData('title')) : ?>
    <div class="block-content">
        <?php
        $er_url = "https://portal.vietcombank.com.vn/Usercontrols/TVPortal.TyGia/pXML.aspx?b=68";
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, $er_url);
        curl_setopt($ch, CURLOPT_FAILONERROR, 1);
        curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_TIMEOUT, 15);
        curl_setopt($ch, CURLOPT_VERBOSE, true);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
        $res = curl_exec($ch);
        curl_close($ch);
        $xml = simplexml_load_string($res);
        $json = json_encode($xml);
        $rs = json_decode($json, TRUE);
        echo '<table id="currency">';
        echo  "<thead><tr>
        <th>Mã ngoại tệ</th>
        <th>Tên ngoại tệ</th>
        <th>Mua vào</th>
        <th>Bán ra</th>
        <th>Chuyển khoản</th>
        </tr></thead>";
        ?>
        <style>
        table,
        tr,
        th,
        td {
            font-size: 13px;
            font-family: 'Roboto', sans-serif;
            border-collapse: collapse;
            border: 1px solid #D6DBDF ;
            text-align: center;
        }
        th{
            padding: 10px; 
            background-color: #1B4F72;
            color: #ECF0F1 ;
            min-width: 100px;
        }
        td{
            height: 30px;
        }

        </style>
        <?php
        foreach ($rs["Exrate"] as $r) {
        $r = $r["@attributes"];
        echo "<tr>";
        echo "<td>";
        echo $r["CurrencyCode"];
        echo "</td>";
        echo "<td>";
        echo $r["CurrencyName"];
        echo "</td>";
        echo "<td>";
        echo $r["Buy"];
        echo "</td>";
        echo "<td>";
        echo $r["Sell"];
        echo "</td>";
        echo "<td>";
        echo $r["Transfer"];
        echo "</td>";
        echo "</tr>";
        }
        echo "</table>";
        ?>
    </div>
    <?php endif; ?>
